"""
출처:프로그래머스,
https://school.programmers.co.kr/learn/courses/30/lessons/164673
"""

# 풀이과정_개선 중
"""
SELECT TITLE, USED_GOODS_BOARD.BOARD_ID, REPLY_ID,USED_GOODS_REPLY.WRITER_ID,USED_GOODS_REPLY.CONTENTS, USED_GOODS_REPLY.CREATED_DATE
    from USED_GOODS_BOARD
        join USED_GOODS_REPLY
        on USED_GOODS_BOARD.BOARD_ID =USED_GOODS_REPLY.BOARD_ID
    where USED_GOODS_REPLY.CREATED_DATE Like "2022-10%"
    order by USED_GOODS_REPLY.CREATED_DATE  asc, USED_GOODS_BOARD.TITLE asc;
"""

# 다른 사람 풀이
"""
SELECT TITLE, BOARD.BOARD_ID, REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS REPLY
LEFT JOIN USED_GOODS_BOARD AS BOARD
ON REPLY.BOARD_ID=BOARD.BOARD_ID
WHERE DATE_FORMAT(BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY REPLY.CREATED_DATE, TITLE```


#2
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE YEAR(UGB.CREATED_DATE) = '2022' AND MONTH(UGB.CREATED_DATE)='10'
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC;
"""