"""
출처:프로그래머스,
https://school.programmers.co.kr/learn/courses/30/lessons/164673
"""

# 풀이과정_개선 중
"""
SELECT TITLE, USED_GOODS_BOARD.BOARD_ID, REPLY_ID,USED_GOODS_REPLY.WRITER_ID,USED_GOODS_REPLY.CONTENTS, USED_GOODS_REPLY.CREATED_DATE
    from USED_GOODS_BOARD
        join USED_GOODS_REPLY
        on USED_GOODS_BOARD.BOARD_ID =USED_GOODS_REPLY.BOARD_ID
    where USED_GOODS_REPLY.CREATED_DATE Like "2022-10%"
    order by USED_GOODS_REPLY.CREATED_DATE  asc, USED_GOODS_BOARD.TITLE asc;
"""